development:
  image_base_url: https://plink-images.s3.amazonaws.com
  mobile_registration_url: http://www.plink.dev/index.cfm?fuseaction=mobile.register

test:
  image_base_url: ''
  mobile_registration_url: http://www.plink.dev/index.cfm?fuseaction=mobile.register

review:
  image_base_url: https://plink-images.s3.amazonaws.com/
  mobile_registration_url: https://www.plink-qa.com/index.cfm?fuseaction=mobile.register

production:
  image_base_url: https://plink-images.s3.amazonaws.com/
  mobile_registration_url: https://www.plink.com/index.cfm?fuseaction=mobile.register
