development:
  image_base_url: ''
  card_add_url: http://www.plink.dev/index.cfm?fuseaction=intuit.selectInstitution
  card_change_url: http://www.plink.dev/index.cfm?fuseaction=intuit.changeBank

test:
  image_base_url: ''
  card_add_url: http://www.plink.dev/index.cfm?fuseaction=intuit.selectInstitution
  card_change_url: http://www.plink.dev/index.cfm?fuseaction=intuit.changeBank

review:
  image_base_url: https://plink-images.s3.amazonaws.com/
  card_add_url: https://www.plink-qa.com/index.cfm?fuseaction=intuit.selectInstitution
  card_change_url: https://www.plink-qa.com/index.cfm?fuseaction=intuit.changeBank

production:
  image_base_url: ''
  card_add_url: https://www.plink.com/index.cfm?fuseaction=intuit.selectInstitution
  card_change_url: https://www.plink.com/index.cfm?fuseaction=intuit.changeBank