development:
  image_base_url: https://plink-images.s3.amazonaws.com
  card_add_url: http://www.plink.dev/index.cfm?fuseaction=intuit.selectInstitution
  card_change_url: http://www.plink.dev/index.cfm?fuseaction=intuit.changeBank
  card_reverify_url: http://www.plink.dev/index.cfm?fuseaction=dialog.additionalInformation

test:
  image_base_url: ''
  card_add_url: http://www.plink.dev/index.cfm?fuseaction=intuit.selectInstitution
  card_change_url: http://www.plink.dev/index.cfm?fuseaction=intuit.changeBank
  card_reverify_url: http://www.plink.dev/index.cfm?fuseaction=dialog.additionalInformation

review:
  image_base_url: http://plink-images.s3.amazonaws.com/
  card_add_url: http://www.plink-qa.com/index.cfm?fuseaction=intuit.selectInstitution
  card_change_url: http://www.plink-qa.com/index.cfm?fuseaction=intuit.changeBank
  card_reverify_url: http://www.plink-qa.com/index.cfm?fuseaction=dialog.additionalInformation

production:
  image_base_url: https://plink-images.s3.amazonaws.com/
  card_add_url: https://www.plink.com/index.cfm?fuseaction=intuit.selectInstitution
  card_change_url: https://www.plink.com/index.cfm?fuseaction=intuit.changeBank
  card_reverify_url: https://www.plink.com/index.cfm?fuseaction=dialog.additionalInformation
